### PR TITLE
Dark mode, as in issue #134

### PR DESCRIPTION
**Pull request by rnbdsh**

### CODE REVIEW

**Comment by marunjar** [comment]
Nice, but i think we should use a single preferenc instead of 2 checkboxes.
Maybe you could already use the android constants (MODE_NIGHT_NO, MODE_NIGHT_YES, MODE_NIGHT_FOLLOW_SYSTEM)
If there's time it would also be cool if theming is changed completely to DayNight, but maybe in another PR

**Comment by rnbdsh** [comment]
the issue with that is backwards-compatibiltiy: PREF_USE_LIGHT_THEME is a boolean propery, and updating the app shouldn't break the previously set setting, and manually adapting it would be quite some extra code.
Also this would require an expanded tri-state selection menu gui, and 2 checkboxes are IMO more convenient than opening a sub-menu.

**Comment by marunjar** [comment]
I just added some code so the new preference is shown only for android 10 and up. Can you give it a try?

**Comment by rnbdsh** [comment]
works for me @ native android 10 + emulator android 9 + emulator android 10

**Pull request merged**
